<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Center Buildout Capacity – GIS Ad Hoc Analyses</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="..\..\site_libs\quarto-contrib\quarto-project\WFRCAnalytics\wfrc-brand\assets\logo\abbreviated\WFRC_logo_abbreviated_color_transparent.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-972b38d173d0a35a8127d8ddd75d40f6.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-c705cb46d44bfdd2d6a1a9bbbf59454d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-972b38d173d0a35a8127d8ddd75d40f6.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-938b977aa7afcaf0e5d1a678dfb25394.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-7f601f039f3fd5ca42992913d2a5218d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-938b977aa7afcaf0e5d1a678dfb25394.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const queryPrefersDark = window.matchMedia('(prefers-color-scheme: dark)');
    const darkModeDefault = queryPrefersDark.matches;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    queryPrefersDark.addEventListener("change", e => {
      if(window.localStorage.getItem("quarto-color-scheme") !== null)
        return;
      const alternate = e.matches
      toggleColorMode(alternate);
      localAlternateSentinel = e.matches ? 'alternate' : 'default'; // this is used alongside local storage!
      toggleGiscusIfUsed(alternate, darkModeDefault);
    });
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="..\..\site_libs\quarto-contrib\quarto-project\WFRCAnalytics\wfrc-brand\assets\logo\abbreviated\WFRC_logo_abbreviated_white_transparent.png" alt="Wasatch Front Regional Council" class="navbar-logo light-content">
    <img src="..\..\site_libs\quarto-contrib\quarto-project\WFRCAnalytics\wfrc-brand\assets\logo\abbreviated\WFRC_logo_abbreviated_white_transparent.png" alt="Wasatch Front Regional Council" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">GIS Ad Hoc Analyses</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../projects/center-buildout-capacity/index.html" aria-current="page"> 
<span class="menu-text">Center Buildout Capacity</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Center Buildout Capacity</h1>
            <p class="subtitle lead">Daybreak, Saratoga Springs Downtown, and The Point</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#purpose" id="toc-purpose" class="nav-link active" data-scroll-target="#purpose">Purpose</a></li>
  <li><a href="#centers-of-interest" id="toc-centers-of-interest" class="nav-link" data-scroll-target="#centers-of-interest">Centers of interest</a></li>
  <li><a href="#load-center-boundaries" id="toc-load-center-boundaries" class="nav-link" data-scroll-target="#load-center-boundaries">Load center boundaries</a></li>
  <li><a href="#remm-parcels-load-and-cache-as-parquet" id="toc-remm-parcels-load-and-cache-as-parquet" class="nav-link" data-scroll-target="#remm-parcels-load-and-cache-as-parquet">REMM parcels: load and cache as parquet</a></li>
  <li><a href="#parcels-within-each-center" id="toc-parcels-within-each-center" class="nav-link" data-scroll-target="#parcels-within-each-center">Parcels within each center</a></li>
  <li><a href="#metric-1-current-year-2025-homes-and-jobs" id="toc-metric-1-current-year-2025-homes-and-jobs" class="nav-link" data-scroll-target="#metric-1-current-year-2025-homes-and-jobs">Metric 1: current year (2025) homes and jobs</a></li>
  <li><a href="#metric-2-2055-forecast-homes-and-jobs" id="toc-metric-2-2055-forecast-homes-and-jobs" class="nav-link" data-scroll-target="#metric-2-2055-forecast-homes-and-jobs">Metric 2: 2055 forecast homes and jobs</a></li>
  <li><a href="#full-remm-capacity-metric-3" id="toc-full-remm-capacity-metric-3" class="nav-link" data-scroll-target="#full-remm-capacity-metric-3">Full REMM capacity (metric 3)</a>
  <ul class="collapse">
  <li><a href="#daybreak-saratoga-springs-downtown-developable-land" id="toc-daybreak-saratoga-springs-downtown-developable-land" class="nav-link" data-scroll-target="#daybreak-saratoga-springs-downtown-developable-land">Daybreak &amp; Saratoga Springs Downtown: developable land</a></li>
  <li><a href="#forecast-development-mix-and-buildout-capacity" id="toc-forecast-development-mix-and-buildout-capacity" class="nav-link" data-scroll-target="#forecast-development-mix-and-buildout-capacity">Forecast development mix and buildout capacity</a></li>
  <li><a href="#the-point-full-buildout" id="toc-the-point-full-buildout" class="nav-link" data-scroll-target="#the-point-full-buildout">The Point: full buildout</a></li>
  </ul></li>
  <li><a href="#sensitivity-duafar-scenarios" id="toc-sensitivity-duafar-scenarios" class="nav-link" data-scroll-target="#sensitivity-duafar-scenarios">Sensitivity: DUA/FAR scenarios</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a>
  <ul class="collapse">
  <li><a href="#csv-exports" id="toc-csv-exports" class="nav-link" data-scroll-target="#csv-exports">CSV exports</a></li>
  <li><a href="#plots" id="toc-plots" class="nav-link" data-scroll-target="#plots">Plots</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">






<section id="purpose" class="level2">
<h2 class="anchored" data-anchor-id="purpose">Purpose</h2>
<p>For three WCV centers – Daybreak, Saratoga Springs Downtown, and The Point – this answers three questions per center:</p>
<ol type="1">
<li><strong>Current year (2025)</strong> homes and jobs – where things stand today.</li>
<li><strong>2055 forecast</strong> homes and jobs – REMM’s own simulated outcome by 2055.</li>
<li><strong>Full REMM capacity</strong> homes and jobs – see <code>## Full REMM capacity</code> below; the method differs by center, since The Point’s is already fully built out by 2055 per REMM (nothing developable left), while Daybreak and Saratoga Springs Downtown still have land redeveloping past 2025 whose <em>additional</em> capacity has to be estimated from density assumptions.</li>
</ol>
<p>Metrics 1 and 2 use one shared calculation for all three centers. See <code>## Summary</code> for the combined results and CSV exports (chart pending).</p>
<p>Spatial joins, filtering, and aggregation below run in geopandas/pandas. The base-year parcels come from <code>remm_base_year_data.gdb</code>, which is cached as GeoParquet on first run (see below) so later runs just read that instead of re-parsing the FileGDB.</p>
</section>
<section id="centers-of-interest" class="level2">
<h2 class="anchored" data-anchor-id="centers-of-interest">Centers of interest</h2>
<p>Single ordered list to extend if more centers are added later. <code>center_boundaries</code> is fetched in full from the REST service (no server-side <code>where</code>), so adding a center here doesn’t require touching <code>sources.yml</code> or re-fetching – just delete <code>_data/processed/centers.parquet</code> to force it to rebuild with the updated list.</p>
<p>Every <code>gpd.read_file()</code> call below passes an OGR SQL <code>where</code> built straight from that list, restricted to “Urban Center” polygons (drops The Point’s separate “Employment District” polygon, since every center in scope for this analysis is its Urban Center polygon).</p>
<div id="1773a064" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>CENTERS_OF_INTEREST <span class="op">=</span> [<span class="st">"Daybreak"</span>, <span class="st">"Saratoga Springs Downtown"</span>, <span class="st">"The Point"</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="load-center-boundaries" class="level2">
<h2 class="anchored" data-anchor-id="load-center-boundaries">Load center boundaries</h2>
<div id="1b004e20" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> gis_adhoc_analyses.layer_cache <span class="im">import</span> ensure_layers</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>L <span class="op">=</span> ensure_layers([<span class="st">"center_boundaries"</span>])</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>centers_preview <span class="op">=</span> gpd.read_file(</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    L[<span class="st">"center_boundaries"</span>],</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    where<span class="op">=</span><span class="ss">f"CenterName IN (</span><span class="sc">{</span><span class="st">', '</span><span class="sc">.</span>join(<span class="bu">map</span>(<span class="bu">repr</span>, CENTERS_OF_INTEREST))<span class="sc">}</span><span class="ss">) AND CenterType = 'Urban Center'"</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>centers_preview[[<span class="st">"CenterName"</span>, <span class="st">"CenterType"</span>, <span class="st">"City"</span>, <span class="st">"DwellingPerAcre"</span>, <span class="st">"NonResFAR"</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Using cached file (1d old): center_boundaries.gpkg</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">CenterName</th>
<th data-quarto-table-cell-role="th">CenterType</th>
<th data-quarto-table-cell-role="th">City</th>
<th data-quarto-table-cell-role="th">DwellingPerAcre</th>
<th data-quarto-table-cell-role="th">NonResFAR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Daybreak</td>
<td>Urban Center</td>
<td>South Jordan</td>
<td>20-100</td>
<td>0.75-4.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>The Point</td>
<td>Urban Center</td>
<td>Draper, Bluffdale</td>
<td>20-100</td>
<td>0.75-4.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Saratoga Springs Downtown</td>
<td>Urban Center</td>
<td>Saratoga Springs</td>
<td>0-100</td>
<td>0.75-4.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="e9571a4e" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>centers_preview.explore(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    column<span class="op">=</span><span class="st">"CenterName"</span>, tooltip<span class="op">=</span>[<span class="st">"CenterName"</span>, <span class="st">"CenterType"</span>, <span class="st">"City"</span>], legend<span class="op">=</span><span class="va">False</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="remm-parcels-load-and-cache-as-parquet" class="level2">
<h2 class="anchored" data-anchor-id="remm-parcels-load-and-cache-as-parquet">REMM parcels: load and cache as parquet</h2>
<div id="94620f35" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>paths <span class="op">=</span> {</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"raw"</span>: Path(<span class="st">"_data/raw"</span>),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"processed"</span>: Path(<span class="st">"_data/processed"</span>),</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>paths[<span class="st">"processed"</span>].mkdir(parents<span class="op">=</span><span class="va">True</span>, exist_ok<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>paths.update({</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"gdb"</span>: paths[<span class="st">"raw"</span>] <span class="op">/</span> <span class="st">"remm"</span> <span class="op">/</span> <span class="st">"remm_base_year_data.gdb"</span>,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"buildings_2055_pkl"</span>: paths[<span class="st">"raw"</span>] <span class="op">/</span> <span class="st">"remm"</span> <span class="op">/</span> <span class="st">"run1842year2055allbuildings.pkl"</span>,</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"progression_2055_pkl"</span>: paths[<span class="st">"raw"</span>] <span class="op">/</span> <span class="st">"remm"</span> <span class="op">/</span> <span class="st">"run_1842_year_2055_parcel_progression_metrics.pkl"</span>,</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"parcels_geoparquet"</span>: paths[<span class="st">"processed"</span>] <span class="op">/</span> <span class="st">"parcels_2023.parquet"</span>,</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"centers_geoparquet"</span>: paths[<span class="st">"processed"</span>] <span class="op">/</span> <span class="st">"centers.parquet"</span>,</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"buildings_2055_parquet"</span>: paths[<span class="st">"processed"</span>] <span class="op">/</span> <span class="st">"buildings_2055.parquet"</span>,</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"progression_2055_parquet"</span>: paths[<span class="st">"processed"</span>] <span class="op">/</span> <span class="st">"progression_2055.parquet"</span>,</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a><span class="co"># one-time read of the two vector sources, cached as GeoParquet so later runs</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="co"># don't re-parse the FileGDB or re-fetch the REST layer. Each cache is a full</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a><span class="co"># replica of every source column -- selecting only the columns actually</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a><span class="co"># needed for a given step happens later, at read time (via `columns=`), not</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a><span class="co"># by trimming what gets cached here.</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="kw">not</span> paths[<span class="st">"parcels_geoparquet"</span>].exists():</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>    parcels_gdf <span class="op">=</span> gpd.read_file(paths[<span class="st">"gdb"</span>], layer<span class="op">=</span><span class="st">"parcels"</span>)</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Split_Factor/MAG_parcel_id mix strings with a couple of real NaNs, which</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>    <span class="co"># pyarrow can't write as a single column type -- nullable string dtype</span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>    <span class="co"># keeps those as actual nulls (not the literal string "nan").</span></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>    parcels_gdf[<span class="st">"Split_Factor"</span>] <span class="op">=</span> parcels_gdf[<span class="st">"Split_Factor"</span>].astype(<span class="st">"string"</span>)</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>    parcels_gdf[<span class="st">"MAG_parcel_id"</span>] <span class="op">=</span> parcels_gdf[<span class="st">"MAG_parcel_id"</span>].astype(<span class="st">"string"</span>)</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>    parcels_gdf.to_parquet(paths[<span class="st">"parcels_geoparquet"</span>])</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="kw">not</span> paths[<span class="st">"centers_geoparquet"</span>].exists():</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>    centers_gdf <span class="op">=</span> gpd.read_file(</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>        L[<span class="st">"center_boundaries"</span>],</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>        where<span class="op">=</span><span class="ss">f"CenterName IN (</span><span class="sc">{</span><span class="st">', '</span><span class="sc">.</span>join(<span class="bu">map</span>(<span class="bu">repr</span>, CENTERS_OF_INTEREST))<span class="sc">}</span><span class="ss">) AND CenterType = 'Urban Center'"</span>,</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>    centers_gdf.to_parquet(paths[<span class="st">"centers_geoparquet"</span>])</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="kw">not</span> paths[<span class="st">"buildings_2055_parquet"</span>].exists():</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>    buildings_full <span class="op">=</span> pd.read_pickle(paths[<span class="st">"buildings_2055_pkl"</span>]).reset_index()</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 'note' mixes real strings with an int 0 sentinel (no dedicated null),</span></span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>    <span class="co"># which pyarrow can't write as a single column type. 0 means "no note", so</span></span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>    <span class="co"># it's replaced with an actual null rather than becoming the string "0".</span></span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>    buildings_full[<span class="st">"note"</span>] <span class="op">=</span> buildings_full[<span class="st">"note"</span>].replace(<span class="dv">0</span>, pd.NA).astype(<span class="st">"string"</span>)</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>    buildings_full.to_parquet(paths[<span class="st">"buildings_2055_parquet"</span>])</span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="kw">not</span> paths[<span class="st">"progression_2055_parquet"</span>].exists():</span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a>    <span class="co"># no mixed-type columns here, so a plain conversion is enough</span></span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a>    pd.read_pickle(paths[<span class="st">"progression_2055_pkl"</span>]).to_parquet(paths[<span class="st">"progression_2055_parquet"</span>])</span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a><span class="co"># only the columns needed for the spatial join below (geometry + acreage/name) --</span></span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a><span class="co"># other columns (max_far, max_dua, DwellingPerAcre, ...) get pulled later, from</span></span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a><span class="co"># the same cached files, only where they're actually used.</span></span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a>parcels <span class="op">=</span> gpd.read_parquet(paths[<span class="st">"parcels_geoparquet"</span>], columns<span class="op">=</span>[<span class="st">"parcel_id"</span>, <span class="st">"parcel_acres"</span>, <span class="st">"geometry"</span>])</span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a>centers <span class="op">=</span> gpd.read_parquet(</span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a>    paths[<span class="st">"centers_geoparquet"</span>], columns<span class="op">=</span>[<span class="st">"CenterName"</span>, <span class="st">"CenterType"</span>, <span class="st">"geometry"</span>]</span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a>).to_crs(parcels.crs)  <span class="co"># centers ships in EPSG:4326 (WGS84) from the REST layer; parcels are in EPSG:26912 (UTM 12N)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="parcels-within-each-center" class="level2">
<h2 class="anchored" data-anchor-id="parcels-within-each-center">Parcels within each center</h2>
<p>Centroid-in-polygon join (not a straight intersection) so a parcel straddling a center boundary is assigned to exactly one center, not double-counted.</p>
<div id="a0e3ca05" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># swap each parcel's polygon for its centroid point -- a polygon can legitimately</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># intersect two centers along a shared edge, but its centroid falls in exactly one.</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>parcel_centroids <span class="op">=</span> parcels.set_geometry(parcels.geometry.centroid)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># predicate="within": keep a parcel only if its centroid point falls inside a</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># center polygon. how="inner" drops parcels whose centroid falls in no center</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># at all (most of the region -- centers are a tiny fraction of all parcels).</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>parcels_in_centers <span class="op">=</span> gpd.sjoin(</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    parcel_centroids, centers[[<span class="st">"CenterName"</span>, <span class="st">"geometry"</span>]], predicate<span class="op">=</span><span class="st">"within"</span>, how<span class="op">=</span><span class="st">"inner"</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>)[[<span class="st">"parcel_id"</span>, <span class="st">"parcel_acres"</span>, <span class="st">"CenterName"</span>]]</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>parcels_per_center <span class="op">=</span> parcels_in_centers.groupby(<span class="st">"CenterName"</span>).agg(</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    n_parcels<span class="op">=</span>(<span class="st">"parcel_id"</span>, <span class="st">"count"</span>), total_acres<span class="op">=</span>(<span class="st">"parcel_acres"</span>, <span class="st">"sum"</span>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>parcels_per_center</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">n_parcels</th>
<th data-quarto-table-cell-role="th">total_acres</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">CenterName</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Daybreak</th>
<td>178</td>
<td>656.151874</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Saratoga Springs Downtown</th>
<td>40</td>
<td>238.963509</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">The Point</th>
<td>64</td>
<td>739.545359</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="14bf0a5d" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># parcels within our 3 centers of interest, reused by every metric below.</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># parcels_in_centers already only contains parcels inside Daybreak, Saratoga</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Springs Downtown, and The Point (centers.parquet was itself built from the</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 3-row where-filtered fetch) -- this isin() is a defensive, explicit filter</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># so downstream cells don't silently depend on that upstream scoping.</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>our_parcels <span class="op">=</span> parcels_in_centers[parcels_in_centers[<span class="st">"CenterName"</span>].isin(CENTERS_OF_INTEREST)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="metric-1-current-year-2025-homes-and-jobs" class="level2">
<h2 class="anchored" data-anchor-id="metric-1-current-year-2025-homes-and-jobs">Metric 1: current year (2025) homes and jobs</h2>
<p>No dedicated 2025 REMM run exists (only “2023” and “2055” pickles), so this derives 2025 by filtering the 2055 run’s buildings table (<code>run1842year2055allbuildings.pkl</code>, one row per <em>building</em>) to <code>year_built &lt;= 2025</code> and summing <code>residential_units</code>/<code>job_spaces</code> per center. One shared calculation for all three centers.</p>
<p><strong>Data quality note:</strong> filtering to <code>year_built &lt;= 2023</code> instead reproduces the dedicated <code>run1842year2023allbuildings.pkl</code> exactly for Daybreak (905 units/2,389 jobs) and Saratoga Springs Downtown (0/0), but not for The Point (2023 pickle: 0 units/2,474 jobs vs.&nbsp;2055-run-filtered: 0/978) – the two REMM runs disagree on The Point’s historical baseline. Proceeding with the uniform <code>year_built &lt;= 2025</code> method regardless: The Point was a state prison site until recently, so a real drop from ~2,474 jobs (2023, pre-closure) to ~978 (2025, post-closure/pre-redevelopment) is a plausible read, not necessarily a data error – consistent with satellite imagery showing The Point still mostly undeveloped today.</p>
<div id="c2e34d4e" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>buildings_2055 <span class="op">=</span> pd.read_parquet(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    paths[<span class="st">"buildings_2055_parquet"</span>],</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    columns<span class="op">=</span>[<span class="st">"parcel_id"</span>, <span class="st">"year_built"</span>, <span class="st">"general_type"</span>, <span class="st">"residential_units"</span>, <span class="st">"job_spaces"</span>],</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>current_year <span class="op">=</span> (</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    buildings_2055[buildings_2055[<span class="st">"year_built"</span>] <span class="op">&lt;=</span> <span class="dv">2025</span>]</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    .merge(our_parcels[[<span class="st">"parcel_id"</span>, <span class="st">"CenterName"</span>]], on<span class="op">=</span><span class="st">"parcel_id"</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    .groupby(<span class="st">"CenterName"</span>)[[<span class="st">"residential_units"</span>, <span class="st">"job_spaces"</span>]]</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">sum</span>()</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    .rename(columns<span class="op">=</span>{<span class="st">"residential_units"</span>: <span class="st">"homes"</span>, <span class="st">"job_spaces"</span>: <span class="st">"jobs"</span>})</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>current_year</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">homes</th>
<th data-quarto-table-cell-role="th">jobs</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">CenterName</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Daybreak</th>
<td>1045.0</td>
<td>3139.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Saratoga Springs Downtown</th>
<td>223.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">The Point</th>
<td>0.0</td>
<td>978.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="metric-2-2055-forecast-homes-and-jobs" class="level2">
<h2 class="anchored" data-anchor-id="metric-2-2055-forecast-homes-and-jobs">Metric 2: 2055 forecast homes and jobs</h2>
<p>REMM’s own simulated outcome by 2055 – sum <code>parcel_progression_metrics</code>’s <code>residential_units</code>/<code>job_spaces</code> (verified reliable per-parcel sums across all of a parcel’s buildings, unlike <code>year_built</code>, which only reflects one representative building) across <strong>all</strong> parcels in each center, not just the ones that redevelop after 2025. Same shared calculation for all three centers – this is exactly what The Point’s full-buildout figure below already is, since REMM shows nothing left developable there by 2055.</p>
<div id="93f36ae2" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>progression_2055 <span class="op">=</span> pd.read_parquet(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    paths[<span class="st">"progression_2055_parquet"</span>], columns<span class="op">=</span>[<span class="st">"parcel_id"</span>, <span class="st">"residential_units"</span>, <span class="st">"job_spaces"</span>]</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>forecast_2055 <span class="op">=</span> (</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    our_parcels.merge(progression_2055, on<span class="op">=</span><span class="st">"parcel_id"</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    .groupby(<span class="st">"CenterName"</span>)[[<span class="st">"residential_units"</span>, <span class="st">"job_spaces"</span>]]</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">sum</span>()</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    .rename(columns<span class="op">=</span>{<span class="st">"residential_units"</span>: <span class="st">"homes"</span>, <span class="st">"job_spaces"</span>: <span class="st">"jobs"</span>})</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>forecast_2055</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">homes</th>
<th data-quarto-table-cell-role="th">jobs</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">CenterName</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Daybreak</th>
<td>7077.0</td>
<td>18110.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Saratoga Springs Downtown</th>
<td>1712.0</td>
<td>4374.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">The Point</th>
<td>6660.0</td>
<td>28382.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="full-remm-capacity-metric-3" class="level2">
<h2 class="anchored" data-anchor-id="full-remm-capacity-metric-3">Full REMM capacity (metric 3)</h2>
<p>Method differs by center:</p>
<ul>
<li><strong>Daybreak &amp; Saratoga Springs Downtown</strong>: developable acreage (parcels with a building <code>year_built &gt; 2025</code>) x forecast res/nonres mix ratio x median density assumptions = <strong>additional</strong> housing units/jobs on top of today’s baseline (metric 1) – not an absolute total by itself. Combined with metric 1 in <code>## Summary</code> to get a comparable absolute figure.</li>
<li><strong>The Point</strong>: no separate development schedule document was ever provided, and The Point is already REMM-modeled, so “the development schedule” here means REMM’s own full-buildout simulation directly (no density-assumption modeling needed) – REMM shows 0 parcels still developable there as of 2055, so this figure already <strong>is</strong> an absolute total, identical to its metric 2 (2055 forecast).</li>
</ul>
<section id="daybreak-saratoga-springs-downtown-developable-land" class="level3">
<h3 class="anchored" data-anchor-id="daybreak-saratoga-springs-downtown-developable-land">Daybreak &amp; Saratoga Springs Downtown: developable land</h3>
<p>Follows the original pseudocode directly: filter the 2055 buildings table to parcels within our centers of interest, keep buildings with <code>year_built &gt; 2025</code>, take the unique parcel ids from that, then sum <code>parcel_acres</code> for those parcels. Computed for all three centers here too (The Point’s result is an exploratory cross-check only – see above).</p>
<p>An earlier version of this shortcut off the parcel-level <code>parcel_progression_metrics</code> table instead, since it already carries a single <code>year_built</code> per parcel. That’s only valid if every building on a parcel always shares the same year/type – checked directly: 162 parcels regionwide have more than one building, 2 of them are in our centers of interest, and in both cases the buildings on that parcel happened to share the same <code>year_built</code>. That was a coincidence of this dataset, not something the data guarantees in general, so this filters at the building level as originally specified rather than relying on it holding elsewhere.</p>
<div id="c9813112" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># inner join: only buildings whose parcel_id is one of our centers' parcels survive.</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>buildings_in_centers <span class="op">=</span> buildings_2055.merge(our_parcels[[<span class="st">"parcel_id"</span>, <span class="st">"CenterName"</span>]], on<span class="op">=</span><span class="st">"parcel_id"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># a parcel can have multiple buildings (see note above) -- .unique() collapses</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># "one row per building built after 2025" down to "one row per qualifying parcel".</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>post_2025_parcel_ids <span class="op">=</span> buildings_in_centers.loc[</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    buildings_in_centers[<span class="st">"year_built"</span>] <span class="op">&gt;</span> <span class="dv">2025</span>, <span class="st">"parcel_id"</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>].unique()</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>developable_land <span class="op">=</span> (</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    our_parcels[our_parcels[<span class="st">"parcel_id"</span>].isin(post_2025_parcel_ids)]</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    .groupby(<span class="st">"CenterName"</span>)</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    .agg(n_parcels<span class="op">=</span>(<span class="st">"parcel_id"</span>, <span class="st">"count"</span>), dev_acres<span class="op">=</span>(<span class="st">"parcel_acres"</span>, <span class="st">"sum"</span>))</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    .reset_index()</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>developable_land</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">CenterName</th>
<th data-quarto-table-cell-role="th">n_parcels</th>
<th data-quarto-table-cell-role="th">dev_acres</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Daybreak</td>
<td>29</td>
<td>135.664032</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Saratoga Springs Downtown</td>
<td>31</td>
<td>158.428793</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>The Point</td>
<td>4</td>
<td>600.890209</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="forecast-development-mix-and-buildout-capacity" class="level3">
<h3 class="anchored" data-anchor-id="forecast-development-mix-and-buildout-capacity">Forecast development mix and buildout capacity</h3>
<section id="forecast-residential-commercialemployment-development-ratio" class="level4">
<h4 class="anchored" data-anchor-id="forecast-residential-commercialemployment-development-ratio">(1) Forecast residential : commercial/employment development ratio</h4>
<p>Sum <code>residential_units</code> and <code>job_spaces</code> from <code>parcel_progression_metrics</code> for the post-2025 developable parcels identified above (2055 run). Full buildout of each center is assumed to follow this same mix, so each center’s total developable acreage is allocated between residential and commercial/employment by this ratio.</p>
<div id="7a72507e" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>dev_mix <span class="op">=</span> (</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    our_parcels[our_parcels[<span class="st">"parcel_id"</span>].isin(post_2025_parcel_ids)][[<span class="st">"parcel_id"</span>, <span class="st">"CenterName"</span>]]</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    .merge(progression_2055, on<span class="op">=</span><span class="st">"parcel_id"</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    .groupby(<span class="st">"CenterName"</span>)[[<span class="st">"residential_units"</span>, <span class="st">"job_spaces"</span>]]</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">sum</span>()</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>dev_mix[<span class="st">"unit_job_ratio"</span>] <span class="op">=</span> dev_mix[<span class="st">"residential_units"</span>] <span class="op">/</span> dev_mix[<span class="st">"job_spaces"</span>]</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co"># res_share/nonres_share are the same ratio re-expressed as shares of a whole</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="co"># (res_share = unit_job_ratio / (unit_job_ratio + 1)) -- this is what actually</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># gets multiplied against acreage below.</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>dev_mix[<span class="st">"res_share"</span>] <span class="op">=</span> dev_mix[<span class="st">"residential_units"</span>] <span class="op">/</span> (dev_mix[<span class="st">"residential_units"</span>] <span class="op">+</span> dev_mix[<span class="st">"job_spaces"</span>])</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>dev_mix[<span class="st">"nonres_share"</span>] <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> dev_mix[<span class="st">"res_share"</span>]</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>dev_mix</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">residential_units</th>
<th data-quarto-table-cell-role="th">job_spaces</th>
<th data-quarto-table-cell-role="th">unit_job_ratio</th>
<th data-quarto-table-cell-role="th">res_share</th>
<th data-quarto-table-cell-role="th">nonres_share</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">CenterName</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Daybreak</th>
<td>6032.0</td>
<td>14971.0</td>
<td>0.402912</td>
<td>0.287197</td>
<td>0.712803</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Saratoga Springs Downtown</th>
<td>1489.0</td>
<td>4374.0</td>
<td>0.340421</td>
<td>0.253966</td>
<td>0.746034</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">The Point</th>
<td>6660.0</td>
<td>27404.0</td>
<td>0.243030</td>
<td>0.195514</td>
<td>0.804486</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="85f736ca" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># split each center's total developable acreage into a residential and a</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># non-residential/employment share, using the res_share/nonres_share</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># computed above -- this is the "assume full buildout follows this same mix" step.</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>acreage_allocation <span class="op">=</span> developable_land.set_index(<span class="st">"CenterName"</span>).loc[</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    CENTERS_OF_INTEREST, [<span class="st">"dev_acres"</span>]</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>].join(dev_mix[[<span class="st">"res_share"</span>, <span class="st">"nonres_share"</span>]])</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>acreage_allocation[<span class="st">"res_acres"</span>] <span class="op">=</span> acreage_allocation[<span class="st">"dev_acres"</span>] <span class="op">*</span> acreage_allocation[<span class="st">"res_share"</span>]</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>acreage_allocation[<span class="st">"nonres_acres"</span>] <span class="op">=</span> acreage_allocation[<span class="st">"dev_acres"</span>] <span class="op">*</span> acreage_allocation[<span class="st">"nonres_share"</span>]</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>acreage_allocation</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">dev_acres</th>
<th data-quarto-table-cell-role="th">res_share</th>
<th data-quarto-table-cell-role="th">nonres_share</th>
<th data-quarto-table-cell-role="th">res_acres</th>
<th data-quarto-table-cell-role="th">nonres_acres</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">CenterName</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Daybreak</th>
<td>135.664032</td>
<td>0.287197</td>
<td>0.712803</td>
<td>38.962312</td>
<td>96.701720</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Saratoga Springs Downtown</th>
<td>158.428793</td>
<td>0.253966</td>
<td>0.746034</td>
<td>40.235455</td>
<td>118.193338</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">The Point</th>
<td>600.890209</td>
<td>0.195514</td>
<td>0.804486</td>
<td>117.482644</td>
<td>483.407564</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="apply-density-assumptions-to-each-acreage-share" class="level4">
<h4 class="anchored" data-anchor-id="apply-density-assumptions-to-each-acreage-share">(2) Apply density assumptions to each acreage share</h4>
<p><strong>Median dwelling-units-per-acre and FAR.</strong> <code>max_far</code>/<code>max_dua</code> live on the <code>parcels</code> table (per-parcel zoning capacity, not a text range), so this takes the statistical median across <em>all</em> parcels in each center – not just the post-2025 developable ones, since the assumption is about the center’s overall zoned capacity, not only what’s forecast to redevelop. Josh noted REMM’s own FAR/DUA-driven numbers assume a parcel develops wall-to-wall (no roads, parking, or common space carved out), so if that assumption changes later, override the values directly here (e.g. <code>capacities.loc["Daybreak", "median_far"] = 2.0</code>) and rerun from this cell down.</p>
<p><strong>Known limitation:</strong> for Daybreak specifically, several of its post-2025 developable parcels are large master-planned “super-parcels” whose actual REMM-simulated density (up to ~280 units/acre on parcels with a recorded <code>max_dua</code> of just 30) far exceeds their generic zoning entitlement – Daybreak’s real approved density (high-rise towers via a specific development agreement) isn’t fully captured by the <code>max_far</code>/<code>max_dua</code> fields. This makes the density-assumption-based capacity estimate understate what REMM’s own simulation already achieves – visible in <code>## Summary</code> below, where <strong>both</strong> Daybreak’s and Saratoga Springs Downtown’s metric 3 homes figures come in <em>below</em> their metric 2 (2055 forecast) despite being meant as a ceiling on top of it. Left as-is for now (including in the <code>## Plots</code> chart below, where it makes the nested bar encoding render oddly for these two) pending a fix to the density assumption itself.</p>
<div id="3344360d" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># our_parcels only has parcel_id/parcel_acres/CenterName -- pull max_far/max_dua</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># from the same parcels cache (already scoped to our_parcels via the merge).</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>capacities <span class="op">=</span> (</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    our_parcels.merge(</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>        gpd.read_parquet(</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>            paths[<span class="st">"parcels_geoparquet"</span>], columns<span class="op">=</span>[<span class="st">"parcel_id"</span>, <span class="st">"max_far"</span>, <span class="st">"max_dua"</span>, <span class="st">"geometry"</span>]</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>        ),</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>        on<span class="op">=</span><span class="st">"parcel_id"</span>,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    .groupby(<span class="st">"CenterName"</span>)[[<span class="st">"max_far"</span>, <span class="st">"max_dua"</span>]]</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    .median()</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    .rename(columns<span class="op">=</span>{<span class="st">"max_far"</span>: <span class="st">"median_far"</span>, <span class="st">"max_dua"</span>: <span class="st">"median_dua"</span>})</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>capacities  <span class="co"># The Point's median_dua is NaN -- none of its parcels have a max_dua entitlement yet; left as-is</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">median_far</th>
<th data-quarto-table-cell-role="th">median_dua</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">CenterName</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Daybreak</th>
<td>7.0</td>
<td>30.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Saratoga Springs Downtown</th>
<td>0.5</td>
<td>10.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">The Point</th>
<td>5.6</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>Median employment density, from FAR and a job-space assumption.</strong> <code>sqft_per_job</code> (needed to turn FAR-driven building sqft into a job count) comes from each center’s own non-residential buildings (all of them, not just post-2025 – there aren’t many non-res buildings in Saratoga Springs Downtown yet, so restricting to post-2025 only left a very thin sample). It turns out to be a fixed constant per building <code>general_type</code> region-wide (Office 633, Retail 374, Industrial 975, …), so the median here reflects each center’s non-res building mix rather than sampling noise.</p>
<div id="5f833cff" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>buildings_full <span class="op">=</span> pd.read_parquet(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    paths[<span class="st">"buildings_2055_parquet"</span>], columns<span class="op">=</span>[<span class="st">"parcel_id"</span>, <span class="st">"general_type"</span>, <span class="st">"sqft_per_job"</span>]</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>).merge(our_parcels[[<span class="st">"parcel_id"</span>, <span class="st">"CenterName"</span>]], on<span class="op">=</span><span class="st">"parcel_id"</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># residential building types excluded here -- sqft_per_job only makes sense</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="co"># for the non-residential/employment share of buildout.</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>nonres_buildings <span class="op">=</span> buildings_full[</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    (buildings_full[<span class="st">"CenterName"</span>].isin(CENTERS_OF_INTEREST))</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="op">&amp;</span> <span class="op">~</span>buildings_full[<span class="st">"general_type"</span>].isin([<span class="st">"SF Residential"</span>, <span class="st">"MF Residential"</span>])</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>sqft_per_job <span class="op">=</span> nonres_buildings.groupby(<span class="st">"CenterName"</span>)[<span class="st">"sqft_per_job"</span>].median().rename(<span class="st">"sqft_per_job"</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>sqft_per_job</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>CenterName
Daybreak                     374.0
Saratoga Springs Downtown    374.0
The Point                    633.0
Name: sqft_per_job, dtype: float64</code></pre>
</div>
</div>
</section>
<section id="estimate-additional-housing-units-and-jobs-at-full-buildout" class="level4">
<h4 class="anchored" data-anchor-id="estimate-additional-housing-units-and-jobs-at-full-buildout">(3) Estimate additional housing units and jobs at full buildout</h4>
<div id="42c63aa2" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>SQFT_PER_ACRE <span class="op">=</span> <span class="dv">43_560</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>capacity <span class="op">=</span> acreage_allocation.join(capacities[[<span class="st">"median_dua"</span>, <span class="st">"median_far"</span>]]).join(sqft_per_job)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># residential: acres x dwelling-units-per-acre = additional housing units</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>capacity[<span class="st">"housing_units"</span>] <span class="op">=</span> capacity[<span class="st">"res_acres"</span>] <span class="op">*</span> capacity[<span class="st">"median_dua"</span>]</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># non-residential: acres x FAR x sqft/acre = total building sqft at full buildout</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>capacity[<span class="st">"nonres_sqft"</span>] <span class="op">=</span> capacity[<span class="st">"nonres_acres"</span>] <span class="op">*</span> capacity[<span class="st">"median_far"</span>] <span class="op">*</span> SQFT_PER_ACRE</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="co"># building sqft / sqft-per-job = additional jobs</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>capacity[<span class="st">"jobs"</span>] <span class="op">=</span> capacity[<span class="st">"nonres_sqft"</span>] <span class="op">/</span> capacity[<span class="st">"sqft_per_job"</span>]</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>capacity[[<span class="st">"dev_acres"</span>, <span class="st">"res_acres"</span>, <span class="st">"nonres_acres"</span>, <span class="st">"housing_units"</span>, <span class="st">"jobs"</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">dev_acres</th>
<th data-quarto-table-cell-role="th">res_acres</th>
<th data-quarto-table-cell-role="th">nonres_acres</th>
<th data-quarto-table-cell-role="th">housing_units</th>
<th data-quarto-table-cell-role="th">jobs</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">CenterName</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Daybreak</th>
<td>135.664032</td>
<td>38.962312</td>
<td>96.701720</td>
<td>1168.869363</td>
<td>78840.343399</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Saratoga Springs Downtown</th>
<td>158.428793</td>
<td>40.235455</td>
<td>118.193338</td>
<td>402.354550</td>
<td>6883.023789</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">The Point</th>
<td>600.890209</td>
<td>117.482644</td>
<td>483.407564</td>
<td>NaN</td>
<td>186288.321705</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
</section>
<section id="the-point-full-buildout" class="level3">
<h3 class="anchored" data-anchor-id="the-point-full-buildout">The Point: full buildout</h3>
<p>Unlike Daybreak/Saratoga Springs Downtown, this doesn’t need acreage allocation or density assumptions: REMM’s simulated buildings already give unit/job counts directly, so this is just a sum, plus a check that nothing’s left undeveloped (rather than an estimate of it). <strong>This is the actual full-capacity figure for The Point</strong> – the developable-land/density- assumption method above was computed for The Point too, but only as an exploratory cross-check (see <code>capacity.loc["The Point"]</code>, which is NaN for housing_units since none of its parcels have a <code>max_dua</code> entitlement yet).</p>
<div id="41674ee7" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># residential_units/job_spaces here are absolute totals as of the 2055 run</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (not "_added" deltas) -- i.e. REMM's full-buildout state, not "new since 2025".</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># developable/year_built/max_far/max_dua are pulled too, for the check below.</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>point_progression <span class="op">=</span> pd.read_parquet(</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    paths[<span class="st">"progression_2055_parquet"</span>],</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    columns<span class="op">=</span>[<span class="st">"parcel_id"</span>, <span class="st">"residential_units"</span>, <span class="st">"job_spaces"</span>, <span class="st">"developable"</span>, <span class="st">"year_built"</span>, <span class="st">"max_far"</span>, <span class="st">"max_dua"</span>],</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>point_parcels <span class="op">=</span> parcels_in_centers[parcels_in_centers[<span class="st">"CenterName"</span>] <span class="op">==</span> <span class="st">"The Point"</span>]</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>point_buildout <span class="op">=</span> point_parcels[[<span class="st">"parcel_id"</span>, <span class="st">"parcel_acres"</span>]].merge(point_progression, on<span class="op">=</span><span class="st">"parcel_id"</span>)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="co"># developable == 1 would mean "still vacant and buildable as of 2055" -- expect</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="co"># none, confirming there's no residual land to separately estimate.</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>still_developable <span class="op">=</span> point_buildout[point_buildout[<span class="st">"developable"</span>] <span class="op">==</span> <span class="dv">1</span>]</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"parcels still flagged developable: </span><span class="sc">{</span><span class="bu">len</span>(still_developable)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="co"># parcels with no building recorded (year_built == 0) are only a gap if they</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a><span class="co"># also have real zoning capacity -- if max_far/max_dua are both 0 too, they're</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a><span class="co"># non-buildable infrastructure (roads, open space), not missed development.</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>unbuilt <span class="op">=</span> point_buildout[point_buildout[<span class="st">"year_built"</span>] <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"parcels never built (</span><span class="sc">{</span>unbuilt[<span class="st">'parcel_acres'</span>]<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.1f}</span><span class="ss"> acres), of which zero-capacity:"</span>,</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>      ((unbuilt[<span class="st">"max_far"</span>] <span class="op">==</span> <span class="dv">0</span>) <span class="op">&amp;</span> (unbuilt[<span class="st">"max_dua"</span>] <span class="op">==</span> <span class="dv">0</span>)).<span class="bu">sum</span>(), <span class="st">"/"</span>, <span class="bu">len</span>(unbuilt))</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>point_capacity <span class="op">=</span> point_buildout[[<span class="st">"residential_units"</span>, <span class="st">"job_spaces"</span>]].<span class="bu">sum</span>().rename({</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">"residential_units"</span>: <span class="st">"housing_units"</span>, <span class="st">"job_spaces"</span>: <span class="st">"jobs"</span></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>point_capacity</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>parcels still flagged developable: 0
parcels never built (31.4 acres), of which zero-capacity: 7 / 7</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>housing_units     6660.0
jobs             28382.0
dtype: float64</code></pre>
</div>
</div>
</section>
</section>
<section id="sensitivity-duafar-scenarios" class="level2">
<h2 class="anchored" data-anchor-id="sensitivity-duafar-scenarios">Sensitivity: DUA/FAR scenarios</h2>
<p>The density assumptions above (<code>median_dua</code>/<code>median_far</code>, from each center’s own zoning entitlements) turn out to badly understate what REMM’s own simulation actually builds on this land. Walking Metric 3’s formula backward from REMM’s 2055 forecast for the post-2025 developable parcels themselves (same <code>res_acres</code>/<code>nonres_acres</code>, just solving for density instead of units) gives implied densities around 155 DUA / 1.3 FAR for Daybreak and 37 DUA / 0.3 FAR for Saratoga Springs Downtown, vs.&nbsp;zoning medians of 30 DUA/7.0 FAR and 10 DUA/0.5 FAR respectively – a real gap, not noise. Rather than committing to one “fixed” density assumption, this applies the same <code>res_acres</code>/<code>nonres_acres</code> x density formula across a fixed grid of alternative densities, so the capacity estimate can be shown as a range instead of a single number.</p>
<p>Applied to all three centers, including The Point – even though its own “current” capacity estimate uses REMM’s full-buildout simulation directly rather than a density assumption (<code>median_dua</code> isn’t even defined for it; none of its parcels carry a <code>max_dua</code> entitlement yet), the constant dua/far scenarios below still apply the same acreage-based formula to it using its own <code>res_acres</code>/<code>nonres_acres</code>/<code>sqft_per_job</code> (computed earlier only as an exploratory cross-check), so it can be compared on the same scenario grid as the other two centers.</p>
<ul>
<li><strong>Residential</strong>: <code>dua</code> = each center’s own zoning median (current method, undefined for The Point) or a fixed 50/100/150 du/acre.</li>
<li><strong>Nonresidential</strong>: <code>far</code> = each center’s own zoning median (current method) or a fixed 0.75/4.0 FAR.</li>
</ul>
<p>For Daybreak/Saratoga Springs Downtown, the “current” row reproduces <code>capacity.loc[center]</code>/<code>housing_capacity</code>/<code>jobs_capacity</code> from above exactly (same formula, same inputs) – included here as a consistency check as much as a scenario. For The Point, “current” instead pulls <code>point_capacity</code> directly, so <code>capacity_added</code> is left blank there: REMM’s full-buildout simulation is a direct absolute total, not decomposed into a 2025-baseline- plus-added-development estimate the way the formula-based scenarios are.</p>
<div id="c1aaf856" class="cell" data-execution_count="16">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>DUA_SCENARIOS <span class="op">=</span> {<span class="st">"current (zoning median)"</span>: <span class="va">None</span>, <span class="st">"dua_50"</span>: <span class="dv">50</span>, <span class="st">"dua_100"</span>: <span class="dv">100</span>, <span class="st">"dua_150"</span>: <span class="dv">150</span>}</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>FAR_SCENARIOS <span class="op">=</span> {<span class="st">"current (zoning median)"</span>: <span class="va">None</span>, <span class="st">"far_0.75"</span>: <span class="fl">0.75</span>, <span class="st">"far_4.0"</span>: <span class="fl">4.0</span>}</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> residential_scenario(center, label, dua):</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> label <span class="op">==</span> <span class="st">"current (zoning median)"</span> <span class="kw">and</span> center <span class="op">==</span> <span class="st">"The Point"</span>:</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> {<span class="st">"assumption_value"</span>: <span class="bu">float</span>(<span class="st">"nan"</span>), <span class="st">"capacity_added"</span>: <span class="bu">float</span>(<span class="st">"nan"</span>),</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>                <span class="st">"capacity_total"</span>: point_capacity[<span class="st">"housing_units"</span>]}</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    dua <span class="op">=</span> capacities.loc[center, <span class="st">"median_dua"</span>] <span class="cf">if</span> dua <span class="kw">is</span> <span class="va">None</span> <span class="cf">else</span> dua</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    added <span class="op">=</span> acreage_allocation.loc[center, <span class="st">"res_acres"</span>] <span class="op">*</span> dua</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {<span class="st">"assumption_value"</span>: dua, <span class="st">"capacity_added"</span>: added, <span class="st">"capacity_total"</span>: added <span class="op">+</span> current_year.loc[center, <span class="st">"homes"</span>]}</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> nonres_scenario(center, label, far):</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> label <span class="op">==</span> <span class="st">"current (zoning median)"</span> <span class="kw">and</span> center <span class="op">==</span> <span class="st">"The Point"</span>:</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> {<span class="st">"assumption_value"</span>: <span class="bu">float</span>(<span class="st">"nan"</span>), <span class="st">"capacity_added"</span>: <span class="bu">float</span>(<span class="st">"nan"</span>),</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>                <span class="st">"capacity_total"</span>: point_capacity[<span class="st">"jobs"</span>]}</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>    far <span class="op">=</span> capacities.loc[center, <span class="st">"median_far"</span>] <span class="cf">if</span> far <span class="kw">is</span> <span class="va">None</span> <span class="cf">else</span> far</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>    added <span class="op">=</span> acreage_allocation.loc[center, <span class="st">"nonres_acres"</span>] <span class="op">*</span> far <span class="op">*</span> SQFT_PER_ACRE <span class="op">/</span> sqft_per_job.loc[center]</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {<span class="st">"assumption_value"</span>: far, <span class="st">"capacity_added"</span>: added, <span class="st">"capacity_total"</span>: added <span class="op">+</span> current_year.loc[center, <span class="st">"jobs"</span>]}</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> center <span class="kw">in</span> CENTERS_OF_INTEREST:</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> label, dua <span class="kw">in</span> DUA_SCENARIOS.items():</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>        row <span class="op">=</span> {<span class="st">"CenterName"</span>: center, <span class="st">"domain"</span>: <span class="st">"residential"</span>, <span class="st">"scenario_label"</span>: label,</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>               <span class="st">"is_current_method"</span>: label.startswith(<span class="st">"current"</span>), <span class="st">"assumption_unit"</span>: <span class="st">"du/acre"</span>,</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>               <span class="st">"capacity_unit"</span>: <span class="st">"housing units"</span>}</span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>        row.update(residential_scenario(center, label, dua))</span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>        rows.append(row)</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> label, far <span class="kw">in</span> FAR_SCENARIOS.items():</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a>        row <span class="op">=</span> {<span class="st">"CenterName"</span>: center, <span class="st">"domain"</span>: <span class="st">"nonres"</span>, <span class="st">"scenario_label"</span>: label,</span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a>               <span class="st">"is_current_method"</span>: label.startswith(<span class="st">"current"</span>), <span class="st">"assumption_unit"</span>: <span class="st">"FAR"</span>,</span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a>               <span class="st">"capacity_unit"</span>: <span class="st">"jobs"</span>}</span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a>        row.update(nonres_scenario(center, label, far))</span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a>        rows.append(row)</span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-38"><a href="#cb20-38" aria-hidden="true" tabindex="-1"></a>sensitivity <span class="op">=</span> pd.DataFrame(rows)[[</span>
<span id="cb20-39"><a href="#cb20-39" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CenterName"</span>, <span class="st">"domain"</span>, <span class="st">"scenario_label"</span>, <span class="st">"is_current_method"</span>,</span>
<span id="cb20-40"><a href="#cb20-40" aria-hidden="true" tabindex="-1"></a>    <span class="st">"assumption_value"</span>, <span class="st">"assumption_unit"</span>, <span class="st">"capacity_added"</span>, <span class="st">"capacity_unit"</span>, <span class="st">"capacity_total"</span>,</span>
<span id="cb20-41"><a href="#cb20-41" aria-hidden="true" tabindex="-1"></a>]]</span>
<span id="cb20-42"><a href="#cb20-42" aria-hidden="true" tabindex="-1"></a>sensitivity</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="15">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">CenterName</th>
<th data-quarto-table-cell-role="th">domain</th>
<th data-quarto-table-cell-role="th">scenario_label</th>
<th data-quarto-table-cell-role="th">is_current_method</th>
<th data-quarto-table-cell-role="th">assumption_value</th>
<th data-quarto-table-cell-role="th">assumption_unit</th>
<th data-quarto-table-cell-role="th">capacity_added</th>
<th data-quarto-table-cell-role="th">capacity_unit</th>
<th data-quarto-table-cell-role="th">capacity_total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Daybreak</td>
<td>residential</td>
<td>current (zoning median)</td>
<td>True</td>
<td>30.00</td>
<td>du/acre</td>
<td>1168.869363</td>
<td>housing units</td>
<td>2213.869363</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Daybreak</td>
<td>residential</td>
<td>dua_50</td>
<td>False</td>
<td>50.00</td>
<td>du/acre</td>
<td>1948.115605</td>
<td>housing units</td>
<td>2993.115605</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Daybreak</td>
<td>residential</td>
<td>dua_100</td>
<td>False</td>
<td>100.00</td>
<td>du/acre</td>
<td>3896.231210</td>
<td>housing units</td>
<td>4941.231210</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Daybreak</td>
<td>residential</td>
<td>dua_150</td>
<td>False</td>
<td>150.00</td>
<td>du/acre</td>
<td>5844.346815</td>
<td>housing units</td>
<td>6889.346815</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Daybreak</td>
<td>nonres</td>
<td>current (zoning median)</td>
<td>True</td>
<td>7.00</td>
<td>FAR</td>
<td>78840.343399</td>
<td>jobs</td>
<td>81979.343399</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Daybreak</td>
<td>nonres</td>
<td>far_0.75</td>
<td>False</td>
<td>0.75</td>
<td>FAR</td>
<td>8447.179650</td>
<td>jobs</td>
<td>11586.179650</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>Daybreak</td>
<td>nonres</td>
<td>far_4.0</td>
<td>False</td>
<td>4.00</td>
<td>FAR</td>
<td>45051.624799</td>
<td>jobs</td>
<td>48190.624799</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>Saratoga Springs Downtown</td>
<td>residential</td>
<td>current (zoning median)</td>
<td>True</td>
<td>10.00</td>
<td>du/acre</td>
<td>402.354550</td>
<td>housing units</td>
<td>625.354550</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>Saratoga Springs Downtown</td>
<td>residential</td>
<td>dua_50</td>
<td>False</td>
<td>50.00</td>
<td>du/acre</td>
<td>2011.772748</td>
<td>housing units</td>
<td>2234.772748</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>Saratoga Springs Downtown</td>
<td>residential</td>
<td>dua_100</td>
<td>False</td>
<td>100.00</td>
<td>du/acre</td>
<td>4023.545495</td>
<td>housing units</td>
<td>4246.545495</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>Saratoga Springs Downtown</td>
<td>residential</td>
<td>dua_150</td>
<td>False</td>
<td>150.00</td>
<td>du/acre</td>
<td>6035.318243</td>
<td>housing units</td>
<td>6258.318243</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>Saratoga Springs Downtown</td>
<td>nonres</td>
<td>current (zoning median)</td>
<td>True</td>
<td>0.50</td>
<td>FAR</td>
<td>6883.023789</td>
<td>jobs</td>
<td>6883.023789</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>Saratoga Springs Downtown</td>
<td>nonres</td>
<td>far_0.75</td>
<td>False</td>
<td>0.75</td>
<td>FAR</td>
<td>10324.535683</td>
<td>jobs</td>
<td>10324.535683</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>Saratoga Springs Downtown</td>
<td>nonres</td>
<td>far_4.0</td>
<td>False</td>
<td>4.00</td>
<td>FAR</td>
<td>55064.190310</td>
<td>jobs</td>
<td>55064.190310</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>The Point</td>
<td>residential</td>
<td>current (zoning median)</td>
<td>True</td>
<td>NaN</td>
<td>du/acre</td>
<td>NaN</td>
<td>housing units</td>
<td>6660.000000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">15</th>
<td>The Point</td>
<td>residential</td>
<td>dua_50</td>
<td>False</td>
<td>50.00</td>
<td>du/acre</td>
<td>5874.132205</td>
<td>housing units</td>
<td>5874.132205</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">16</th>
<td>The Point</td>
<td>residential</td>
<td>dua_100</td>
<td>False</td>
<td>100.00</td>
<td>du/acre</td>
<td>11748.264411</td>
<td>housing units</td>
<td>11748.264411</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">17</th>
<td>The Point</td>
<td>residential</td>
<td>dua_150</td>
<td>False</td>
<td>150.00</td>
<td>du/acre</td>
<td>17622.396616</td>
<td>housing units</td>
<td>17622.396616</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">18</th>
<td>The Point</td>
<td>nonres</td>
<td>current (zoning median)</td>
<td>True</td>
<td>NaN</td>
<td>FAR</td>
<td>NaN</td>
<td>jobs</td>
<td>28382.000000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">19</th>
<td>The Point</td>
<td>nonres</td>
<td>far_0.75</td>
<td>False</td>
<td>0.75</td>
<td>FAR</td>
<td>24949.328800</td>
<td>jobs</td>
<td>25927.328800</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">20</th>
<td>The Point</td>
<td>nonres</td>
<td>far_4.0</td>
<td>False</td>
<td>4.00</td>
<td>FAR</td>
<td>133063.086932</td>
<td>jobs</td>
<td>134041.086932</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<div id="c3a5c1ef" class="cell" data-execution_count="17">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Full REMM capacity, as an absolute total comparable to metrics 1/2:</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Daybreak/Saratoga Springs Downtown = current year + additional capacity</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co"># (task 2's density-assumption estimate); The Point = its own full-buildout</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co"># sum directly (task 3), NOT the exploratory `capacity.loc["The Point"]` row.</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>housing_capacity <span class="op">=</span> pd.Series(index<span class="op">=</span>CENTERS_OF_INTEREST, dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>jobs_capacity <span class="op">=</span> pd.Series(index<span class="op">=</span>CENTERS_OF_INTEREST, dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> center <span class="kw">in</span> [<span class="st">"Daybreak"</span>, <span class="st">"Saratoga Springs Downtown"</span>]:</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>    housing_capacity[center] <span class="op">=</span> current_year.loc[center, <span class="st">"homes"</span>] <span class="op">+</span> capacity.loc[center, <span class="st">"housing_units"</span>]</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>    jobs_capacity[center] <span class="op">=</span> current_year.loc[center, <span class="st">"jobs"</span>] <span class="op">+</span> capacity.loc[center, <span class="st">"jobs"</span>]</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>housing_capacity[<span class="st">"The Point"</span>] <span class="op">=</span> point_capacity[<span class="st">"housing_units"</span>]</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>jobs_capacity[<span class="st">"The Point"</span>] <span class="op">=</span> point_capacity[<span class="st">"jobs"</span>]</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>summary <span class="op">=</span> pd.DataFrame({</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"total_acres"</span>: parcels_per_center[<span class="st">"total_acres"</span>],</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"housing_2025"</span>: current_year[<span class="st">"homes"</span>],</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"jobs_2025"</span>: current_year[<span class="st">"jobs"</span>],</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"housing_2055"</span>: forecast_2055[<span class="st">"homes"</span>],</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"jobs_2055"</span>: forecast_2055[<span class="st">"jobs"</span>],</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"housing_capacity"</span>: housing_capacity,</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">"jobs_capacity"</span>: jobs_capacity,</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>}).loc[CENTERS_OF_INTEREST]</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>summary.index.name <span class="op">=</span> <span class="st">"CenterName"</span></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="16">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">total_acres</th>
<th data-quarto-table-cell-role="th">housing_2025</th>
<th data-quarto-table-cell-role="th">jobs_2025</th>
<th data-quarto-table-cell-role="th">housing_2055</th>
<th data-quarto-table-cell-role="th">jobs_2055</th>
<th data-quarto-table-cell-role="th">housing_capacity</th>
<th data-quarto-table-cell-role="th">jobs_capacity</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">CenterName</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Daybreak</th>
<td>656.151874</td>
<td>1045.0</td>
<td>3139.0</td>
<td>7077.0</td>
<td>18110.0</td>
<td>2213.869363</td>
<td>81979.343399</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Saratoga Springs Downtown</th>
<td>238.963509</td>
<td>223.0</td>
<td>0.0</td>
<td>1712.0</td>
<td>4374.0</td>
<td>625.354550</td>
<td>6883.023789</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">The Point</th>
<td>739.545359</td>
<td>0.0</td>
<td>978.0</td>
<td>6660.0</td>
<td>28382.0</td>
<td>6660.000000</td>
<td>28382.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>Note:</strong> both Daybreak’s <code>housing_capacity</code> (2,214 vs.&nbsp;<code>housing_2055</code> 7,077) and Saratoga Springs Downtown’s (625 vs.&nbsp;1,712) come in <em>below</em> their own 2055 forecast – see the “known limitation” callout above. The density-assumption method understates real achievable density for both; REMM’s own 2055 simulation is itself evidence of what’s actually achievable. Decided to implement the <code>## Plots</code> housing chart as-is despite this (no flooring at <code>max(capacity, housing_2055)</code>), accepting that the nested bar encoding renders oddly for these two centers until the density assumption itself is revisited.</p>
<section id="csv-exports" class="level3">
<h3 class="anchored" data-anchor-id="csv-exports">CSV exports</h3>
<div id="4ee13d32" class="cell" data-execution_count="18">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>output_dir <span class="op">=</span> Path(<span class="st">"output"</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>output_dir.mkdir(exist_ok<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>summary.to_csv(output_dir <span class="op">/</span> <span class="st">"center_buildout_summary.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="40c8cc76" class="cell" data-execution_count="19">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># every intermediate number computed along the way, one row per center, so</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># follow-up questions can be answered without re-running the notebook.</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>detail <span class="op">=</span> pd.DataFrame({</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"total_acres"</span>: parcels_per_center[<span class="st">"total_acres"</span>],</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"dev_acres"</span>: developable_land.set_index(<span class="st">"CenterName"</span>)[<span class="st">"dev_acres"</span>],</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"unit_job_ratio"</span>: dev_mix[<span class="st">"unit_job_ratio"</span>],</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"res_share"</span>: dev_mix[<span class="st">"res_share"</span>],</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"res_acres"</span>: acreage_allocation[<span class="st">"res_acres"</span>],</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"housing_2025"</span>: current_year[<span class="st">"homes"</span>],</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"housing_2055"</span>: forecast_2055[<span class="st">"homes"</span>],</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"median_dua"</span>: capacities[<span class="st">"median_dua"</span>],</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"housing_capacity"</span>: housing_capacity,</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"nonres_share"</span>: dev_mix[<span class="st">"nonres_share"</span>],</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"nonres_acres"</span>: acreage_allocation[<span class="st">"nonres_acres"</span>],</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"jobs_2025"</span>: current_year[<span class="st">"jobs"</span>],</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"jobs_2055"</span>: forecast_2055[<span class="st">"jobs"</span>],</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"median_far"</span>: capacities[<span class="st">"median_far"</span>],</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"sqft_per_job"</span>: sqft_per_job,</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"jobs_capacity"</span>: jobs_capacity,</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>}).reindex(CENTERS_OF_INTEREST)</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>detail.index.name <span class="op">=</span> <span class="st">"CenterName"</span></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>detail.to_csv(output_dir <span class="op">/</span> <span class="st">"center_buildout_detail.csv"</span>)</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>detail</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="18">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">total_acres</th>
<th data-quarto-table-cell-role="th">dev_acres</th>
<th data-quarto-table-cell-role="th">unit_job_ratio</th>
<th data-quarto-table-cell-role="th">res_share</th>
<th data-quarto-table-cell-role="th">res_acres</th>
<th data-quarto-table-cell-role="th">housing_2025</th>
<th data-quarto-table-cell-role="th">housing_2055</th>
<th data-quarto-table-cell-role="th">median_dua</th>
<th data-quarto-table-cell-role="th">housing_capacity</th>
<th data-quarto-table-cell-role="th">nonres_share</th>
<th data-quarto-table-cell-role="th">nonres_acres</th>
<th data-quarto-table-cell-role="th">jobs_2025</th>
<th data-quarto-table-cell-role="th">jobs_2055</th>
<th data-quarto-table-cell-role="th">median_far</th>
<th data-quarto-table-cell-role="th">sqft_per_job</th>
<th data-quarto-table-cell-role="th">jobs_capacity</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">CenterName</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Daybreak</th>
<td>656.151874</td>
<td>135.664032</td>
<td>0.402912</td>
<td>0.287197</td>
<td>38.962312</td>
<td>1045.0</td>
<td>7077.0</td>
<td>30.0</td>
<td>2213.869363</td>
<td>0.712803</td>
<td>96.701720</td>
<td>3139.0</td>
<td>18110.0</td>
<td>7.0</td>
<td>374.0</td>
<td>81979.343399</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Saratoga Springs Downtown</th>
<td>238.963509</td>
<td>158.428793</td>
<td>0.340421</td>
<td>0.253966</td>
<td>40.235455</td>
<td>223.0</td>
<td>1712.0</td>
<td>10.0</td>
<td>625.354550</td>
<td>0.746034</td>
<td>118.193338</td>
<td>0.0</td>
<td>4374.0</td>
<td>0.5</td>
<td>374.0</td>
<td>6883.023789</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">The Point</th>
<td>739.545359</td>
<td>600.890209</td>
<td>0.243030</td>
<td>0.195514</td>
<td>117.482644</td>
<td>0.0</td>
<td>6660.0</td>
<td>NaN</td>
<td>6660.000000</td>
<td>0.804486</td>
<td>483.407564</td>
<td>978.0</td>
<td>28382.0</td>
<td>5.6</td>
<td>633.0</td>
<td>28382.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="3a0d9867" class="cell" data-execution_count="20">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>sensitivity.to_csv(output_dir <span class="op">/</span> <span class="st">"center_buildout_sensitivity.csv"</span>, index<span class="op">=</span><span class="va">False</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="plots" class="level3">
<h3 class="anchored" data-anchor-id="plots">Plots</h3>
<p>Both employment and housing render below, each extended with the sensitivity scenarios from <code>## Sensitivity: DUA/FAR scenarios</code> as an overlay on top of the original chart – not a separate chart – so the density-assumption uncertainty shows up right on the same bars analysts already read.</p>
<p>Horizontal bars, editorial styling inspired by Tanya Shapiro’s ggplot work: left-aligned bold title/subtitle, direct value labels instead of relying on axis ticks, minimal chart junk (no spines, no gridlines), and the WFRC brand’s own typeface (Poppins) instead of matplotlib’s default font – <code>Inter</code> (the brand’s heading font) turned out to only be installed as a variable font at weight 400, so <code>Poppins SemiBold</code> (a proper static weight) carries the title/value labels instead, keeping one cohesive typeface throughout rather than mixing families. Centers are fixed to <code>index.qmd</code>’s own canonical <code>CENTERS_OF_INTEREST</code> order (Daybreak, Saratoga Springs Downtown, The Point) in both charts – rather than each chart sorting by its own capacity column – so a center sits in the same row in both.</p>
<p>Each bar is a <strong>Meter</strong>-style nested encoding (see the <code>dataviz</code> skill: fill = value, track = a lighter step of the same hue), extended from 2 tiers to 3, with all three values labeled (not just capacity):</p>
<ul>
<li><strong>Track</strong> (full bar length): full REMM capacity – lightest tint of the center’s hue.</li>
<li><strong>Hatch overlay</strong> (0 to the 2055 figure): tone-on-tone diagonal texture – how much of that capacity REMM’s own simulation reaches by 2055. Skipped for The Point, where 2055 forecast == capacity exactly (nothing left developable), to avoid labeling the same value twice. For Daybreak and Saratoga Springs Downtown’s <em>housing</em> chart specifically, <code>housing_2055</code> is actually <em>above</em> <code>housing_capacity</code> (the density-assumption method’s known limitation, discussed above) – an honest reflection of that, not a rendering bug, so the hatch overlay extends past the light-shade track there instead of nesting inside it.</li>
</ul>
<p>Colors are 3 categorical hues from the WFRC brand’s Core Palette (<code>blue #036fa8</code>, <code>orange #ea7b00</code>, <code>green #007426</code>), chosen over the “Wasatch Choice Center” colors since all three centers share the same <code>CenterType</code> and would collide under that scheme. Validated with the <code>dataviz</code> skill’s <code>validate_palette.js</code> six-checks script: all pass except a contrast WARN on orange (2.79, below 3:1) – satisfied by the visible value labels here and the table above, per the skill’s relief rule.</p>
<p><strong>Sensitivity overlay</strong>, drawn directly on top of each existing bar:</p>
<ul>
<li>A small vertical <strong>tick</strong> at each alternate scenario’s <code>capacity_total</code>, plus a thin neutral <strong>bracket</strong> connecting the tested range into one span. Ticks (and their value labels) get their own fixed color <em>per scenario</em> – not per center, since centers are already distinguished by row + the tier hues – from a light-to-dark purple <strong>ordinal ramp</strong> (50 &lt; 100 &lt; 150 du/ac; 0.75 &lt; 4.0 FAR is an ordered category, not an arbitrary categorical palette), with a second legend row mapping each color to its scenario.</li>
<li><strong>The Point’s</strong> <code>dua_100</code>/<code>dua_150</code>/<code>far_4.0</code> scenarios are genuine order-of-magnitude outliers (its land area dwarfs Daybreak/SSD’s, so a flat per-acre assumption blows past everything else) – stretching the shared axis to fit them would compress every other bar into a sliver, so the axis instead caps at 1.3x the existing capacity-tier max, and anything past that renders as an off-scale <code>&gt;</code> marker with an asterisked value instead of distorting the whole plot.</li>
<li>Every label – the pre-existing 2025/2055/capacity labels and the new scenario labels – draws at a higher <code>zorder</code> than the bracket/tick lines, and the bold capacity label additionally gets a surface-colored <code>path_effects</code> halo: the tested range regularly extends past capacity, so without this the bracket line would render <em>through</em> that number instead of behind it.</li>
</ul>
<div id="6dbfd859" class="cell" data-execution_count="21">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.patheffects <span class="im">as</span> pe</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.lines <span class="im">import</span> Line2D</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.patches <span class="im">import</span> Patch</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>matplotlib.rcParams[<span class="st">"hatch.linewidth"</span>] <span class="op">=</span> <span class="fl">2.2</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>matplotlib.rcParams[<span class="st">"font.family"</span>] <span class="op">=</span> <span class="st">"Poppins"</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>CENTER_COLORS <span class="op">=</span> {</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Daybreak"</span>: <span class="st">"#036fa8"</span>,</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Saratoga Springs Downtown"</span>: <span class="st">"#ea7b00"</span>,</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"The Point"</span>: <span class="st">"#007426"</span>,</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>CENTER_LABELS <span class="op">=</span> {</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Daybreak"</span>: <span class="st">"Daybreak"</span>,</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Saratoga Springs Downtown"</span>: <span class="st">"Saratoga Springs</span><span class="ch">\n</span><span class="st">Downtown"</span>,</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"The Point"</span>: <span class="st">"The Point"</span>,</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>SURFACE <span class="op">=</span> <span class="st">"#fcfcfb"</span></span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>TEXT_PRIMARY <span class="op">=</span> <span class="st">"#151515"</span></span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>TEXT_MUTED <span class="op">=</span> <span class="st">"#7f7a76"</span></span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>BRACKET_INK <span class="op">=</span> <span class="st">"#a19b94"</span>  <span class="co"># neutral connecting line -- just context, not identity</span></span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>LEFT, RIGHT <span class="op">=</span> <span class="fl">0.205</span>, <span class="fl">0.92</span></span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Scenarios get their own fixed hue, one shared ramp reused across both</span></span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a><span class="co"># domains and all three centers. Purple family: distinct from every</span></span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a><span class="co"># CENTER_COLORS hue and from the neutral bracket ink.</span></span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a>SCENARIO_LOW, SCENARIO_MID, SCENARIO_HIGH <span class="op">=</span> <span class="st">"#b088d9"</span>, <span class="st">"#8347c2"</span>, <span class="st">"#5b2c86"</span></span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>DOMAIN_CFG <span class="op">=</span> {</span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">"jobs"</span>: {</span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a>        <span class="st">"col"</span>: <span class="st">"nonres"</span>, <span class="st">"summary_cap"</span>: <span class="st">"jobs_capacity"</span>, <span class="st">"summary_2055"</span>: <span class="st">"jobs_2055"</span>, <span class="st">"summary_2025"</span>: <span class="st">"jobs_2025"</span>,</span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a>        <span class="st">"alt_scenarios"</span>: [<span class="st">"far_0.75"</span>, <span class="st">"far_4.0"</span>], <span class="st">"alt_ticks"</span>: [<span class="st">"0.75 FAR"</span>, <span class="st">"4.0 FAR"</span>],</span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a>        <span class="st">"scenario_colors"</span>: {<span class="st">"0.75 FAR"</span>: SCENARIO_LOW, <span class="st">"4.0 FAR"</span>: SCENARIO_HIGH},</span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a>        <span class="st">"title"</span>: <span class="st">"Employment capacity across three WCV centers"</span>,</span>
<span id="cb25-38"><a href="#cb25-38" aria-hidden="true" tabindex="-1"></a>        <span class="st">"subtitle"</span>: <span class="st">"Current jobs (2025), REMM's 2055 forecast, full buildout capacity, and alternate FAR scenarios"</span>,</span>
<span id="cb25-39"><a href="#cb25-39" aria-hidden="true" tabindex="-1"></a>        <span class="st">"out"</span>: <span class="st">"employment_buildout.png"</span>,</span>
<span id="cb25-40"><a href="#cb25-40" aria-hidden="true" tabindex="-1"></a>    },</span>
<span id="cb25-41"><a href="#cb25-41" aria-hidden="true" tabindex="-1"></a>    <span class="st">"housing"</span>: {</span>
<span id="cb25-42"><a href="#cb25-42" aria-hidden="true" tabindex="-1"></a>        <span class="st">"col"</span>: <span class="st">"residential"</span>, <span class="st">"summary_cap"</span>: <span class="st">"housing_capacity"</span>, <span class="st">"summary_2055"</span>: <span class="st">"housing_2055"</span>, <span class="st">"summary_2025"</span>: <span class="st">"housing_2025"</span>,</span>
<span id="cb25-43"><a href="#cb25-43" aria-hidden="true" tabindex="-1"></a>        <span class="st">"alt_scenarios"</span>: [<span class="st">"dua_50"</span>, <span class="st">"dua_100"</span>, <span class="st">"dua_150"</span>], <span class="st">"alt_ticks"</span>: [<span class="st">"50 du/ac"</span>, <span class="st">"100 du/ac"</span>, <span class="st">"150 du/ac"</span>],</span>
<span id="cb25-44"><a href="#cb25-44" aria-hidden="true" tabindex="-1"></a>        <span class="st">"scenario_colors"</span>: {<span class="st">"50 du/ac"</span>: SCENARIO_LOW, <span class="st">"100 du/ac"</span>: SCENARIO_MID, <span class="st">"150 du/ac"</span>: SCENARIO_HIGH},</span>
<span id="cb25-45"><a href="#cb25-45" aria-hidden="true" tabindex="-1"></a>        <span class="st">"title"</span>: <span class="st">"Housing capacity across three WCV centers"</span>,</span>
<span id="cb25-46"><a href="#cb25-46" aria-hidden="true" tabindex="-1"></a>        <span class="st">"subtitle"</span>: <span class="st">"Current homes (2025), REMM's 2055 forecast, full buildout capacity, and alternate DUA scenarios"</span>,</span>
<span id="cb25-47"><a href="#cb25-47" aria-hidden="true" tabindex="-1"></a>        <span class="st">"out"</span>: <span class="st">"housing_buildout.png"</span>,</span>
<span id="cb25-48"><a href="#cb25-48" aria-hidden="true" tabindex="-1"></a>    },</span>
<span id="cb25-49"><a href="#cb25-49" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-50"><a href="#cb25-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-51"><a href="#cb25-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-52"><a href="#cb25-52" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> lighten(hex_color, amount):</span>
<span id="cb25-53"><a href="#cb25-53" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Blend hex_color toward white by `amount` (0=no change, 1=white)."""</span></span>
<span id="cb25-54"><a href="#cb25-54" aria-hidden="true" tabindex="-1"></a>    hex_color <span class="op">=</span> hex_color.lstrip(<span class="st">"#"</span>)</span>
<span id="cb25-55"><a href="#cb25-55" aria-hidden="true" tabindex="-1"></a>    r, g, b <span class="op">=</span> (<span class="bu">int</span>(hex_color[i:i <span class="op">+</span> <span class="dv">2</span>], <span class="dv">16</span>) <span class="cf">for</span> i <span class="kw">in</span> (<span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">4</span>))</span>
<span id="cb25-56"><a href="#cb25-56" aria-hidden="true" tabindex="-1"></a>    r, g, b <span class="op">=</span> (<span class="bu">int</span>(c <span class="op">+</span> (<span class="dv">255</span> <span class="op">-</span> c) <span class="op">*</span> amount) <span class="cf">for</span> c <span class="kw">in</span> (r, g, b))</span>
<span id="cb25-57"><a href="#cb25-57" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="ss">f"#</span><span class="sc">{</span>r<span class="sc">:02x}{</span>g<span class="sc">:02x}{</span>b<span class="sc">:02x}</span><span class="ss">"</span></span>
<span id="cb25-58"><a href="#cb25-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-59"><a href="#cb25-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-60"><a href="#cb25-60" aria-hidden="true" tabindex="-1"></a><span class="co"># fixed to CENTERS_OF_INTEREST, reversed since barh renders list[0] at the</span></span>
<span id="cb25-61"><a href="#cb25-61" aria-hidden="true" tabindex="-1"></a><span class="co"># bottom row and list[-1] at the top -- this reads top-to-bottom as</span></span>
<span id="cb25-62"><a href="#cb25-62" aria-hidden="true" tabindex="-1"></a><span class="co"># Daybreak, Saratoga Springs Downtown, The Point in both charts.</span></span>
<span id="cb25-63"><a href="#cb25-63" aria-hidden="true" tabindex="-1"></a>CENTER_ORDER <span class="op">=</span> <span class="bu">list</span>(<span class="bu">reversed</span>(CENTERS_OF_INTEREST))</span>
<span id="cb25-64"><a href="#cb25-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-65"><a href="#cb25-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-66"><a href="#cb25-66" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> make_chart(domain_key):</span>
<span id="cb25-67"><a href="#cb25-67" aria-hidden="true" tabindex="-1"></a>    cfg <span class="op">=</span> DOMAIN_CFG[domain_key]</span>
<span id="cb25-68"><a href="#cb25-68" aria-hidden="true" tabindex="-1"></a>    alt <span class="op">=</span> sensitivity[sensitivity[<span class="st">"domain"</span>] <span class="op">==</span> cfg[<span class="st">"col"</span>]].set_index([<span class="st">"CenterName"</span>, <span class="st">"scenario_label"</span>])[<span class="st">"capacity_total"</span>]</span>
<span id="cb25-69"><a href="#cb25-69" aria-hidden="true" tabindex="-1"></a>    order <span class="op">=</span> CENTER_ORDER</span>
<span id="cb25-70"><a href="#cb25-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-71"><a href="#cb25-71" aria-hidden="true" tabindex="-1"></a>    <span class="co"># modest extra row spacing (vs. a plain unit-spaced chart) so the</span></span>
<span id="cb25-72"><a href="#cb25-72" aria-hidden="true" tabindex="-1"></a>    <span class="co"># per-scenario tick labels below each bar have room to breathe</span></span>
<span id="cb25-73"><a href="#cb25-73" aria-hidden="true" tabindex="-1"></a>    row_gap <span class="op">=</span> <span class="fl">1.2</span></span>
<span id="cb25-74"><a href="#cb25-74" aria-hidden="true" tabindex="-1"></a>    fig_height <span class="op">=</span> <span class="fl">5.9</span> <span class="op">+</span> (row_gap <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> <span class="fl">1.6</span></span>
<span id="cb25-75"><a href="#cb25-75" aria-hidden="true" tabindex="-1"></a>    ys <span class="op">=</span> [i <span class="op">*</span> row_gap <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(order))]</span>
<span id="cb25-76"><a href="#cb25-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-77"><a href="#cb25-77" aria-hidden="true" tabindex="-1"></a>    fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">9.5</span>, fig_height), dpi<span class="op">=</span><span class="dv">140</span>)</span>
<span id="cb25-78"><a href="#cb25-78" aria-hidden="true" tabindex="-1"></a>    fig.patch.set_facecolor(SURFACE)</span>
<span id="cb25-79"><a href="#cb25-79" aria-hidden="true" tabindex="-1"></a>    ax.set_facecolor(SURFACE)</span>
<span id="cb25-80"><a href="#cb25-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-81"><a href="#cb25-81" aria-hidden="true" tabindex="-1"></a>    bar_height <span class="op">=</span> <span class="fl">0.5</span></span>
<span id="cb25-82"><a href="#cb25-82" aria-hidden="true" tabindex="-1"></a>    base_max <span class="op">=</span> summary[cfg[<span class="st">"summary_cap"</span>]].<span class="bu">max</span>()</span>
<span id="cb25-83"><a href="#cb25-83" aria-hidden="true" tabindex="-1"></a>    clip_limit <span class="op">=</span> base_max <span class="op">*</span> <span class="fl">1.3</span></span>
<span id="cb25-84"><a href="#cb25-84" aria-hidden="true" tabindex="-1"></a>    in_range_alts <span class="op">=</span> [alt[(c, s)] <span class="cf">for</span> c <span class="kw">in</span> order <span class="cf">for</span> s <span class="kw">in</span> cfg[<span class="st">"alt_scenarios"</span>] <span class="cf">if</span> alt[(c, s)] <span class="op">&lt;=</span> clip_limit]</span>
<span id="cb25-85"><a href="#cb25-85" aria-hidden="true" tabindex="-1"></a>    xmax <span class="op">=</span> <span class="bu">max</span>([base_max, <span class="op">*</span>in_range_alts])</span>
<span id="cb25-86"><a href="#cb25-86" aria-hidden="true" tabindex="-1"></a>    any_clipped <span class="op">=</span> <span class="va">False</span></span>
<span id="cb25-87"><a href="#cb25-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-88"><a href="#cb25-88" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, center <span class="kw">in</span> <span class="bu">enumerate</span>(order):</span>
<span id="cb25-89"><a href="#cb25-89" aria-hidden="true" tabindex="-1"></a>        y <span class="op">=</span> ys[i]</span>
<span id="cb25-90"><a href="#cb25-90" aria-hidden="true" tabindex="-1"></a>        hue <span class="op">=</span> CENTER_COLORS[center]</span>
<span id="cb25-91"><a href="#cb25-91" aria-hidden="true" tabindex="-1"></a>        cap <span class="op">=</span> summary.loc[center, cfg[<span class="st">"summary_cap"</span>]]</span>
<span id="cb25-92"><a href="#cb25-92" aria-hidden="true" tabindex="-1"></a>        forecast <span class="op">=</span> summary.loc[center, cfg[<span class="st">"summary_2055"</span>]]</span>
<span id="cb25-93"><a href="#cb25-93" aria-hidden="true" tabindex="-1"></a>        current <span class="op">=</span> summary.loc[center, cfg[<span class="st">"summary_2025"</span>]]</span>
<span id="cb25-94"><a href="#cb25-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-95"><a href="#cb25-95" aria-hidden="true" tabindex="-1"></a>        ax.barh(y, cap, height<span class="op">=</span>bar_height, color<span class="op">=</span>lighten(hue, <span class="fl">0.8</span>), zorder<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb25-96"><a href="#cb25-96" aria-hidden="true" tabindex="-1"></a>        ax.barh(y, forecast, height<span class="op">=</span>bar_height, facecolor<span class="op">=</span><span class="st">"none"</span>, hatch<span class="op">=</span><span class="st">"///"</span>, edgecolor<span class="op">=</span>lighten(hue, <span class="fl">0.25</span>), linewidth<span class="op">=</span><span class="dv">0</span>, zorder<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb25-97"><a href="#cb25-97" aria-hidden="true" tabindex="-1"></a>        ax.barh(y, current, height<span class="op">=</span>bar_height, color<span class="op">=</span>hue, zorder<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb25-98"><a href="#cb25-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-99"><a href="#cb25-99" aria-hidden="true" tabindex="-1"></a>        top_y <span class="op">=</span> y <span class="op">+</span> bar_height <span class="op">/</span> <span class="dv">2</span></span>
<span id="cb25-100"><a href="#cb25-100" aria-hidden="true" tabindex="-1"></a>        LABEL_Z <span class="op">=</span> <span class="dv">6</span>  <span class="co"># every label out-ranks the bracket (4) and tick (5) lines</span></span>
<span id="cb25-101"><a href="#cb25-101" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> current <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb25-102"><a href="#cb25-102" aria-hidden="true" tabindex="-1"></a>            ax.text(current, top_y <span class="op">+</span> <span class="fl">0.07</span>, <span class="ss">f"</span><span class="sc">{</span>current<span class="sc">:,.0f}</span><span class="ss">"</span>, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"bottom"</span>, fontsize<span class="op">=</span><span class="fl">8.5</span>, color<span class="op">=</span>TEXT_MUTED, zorder<span class="op">=</span>LABEL_Z)</span>
<span id="cb25-103"><a href="#cb25-103" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb25-104"><a href="#cb25-104" aria-hidden="true" tabindex="-1"></a>            ax.text(current, top_y <span class="op">+</span> <span class="fl">0.07</span>, <span class="st">"0"</span>, ha<span class="op">=</span><span class="st">"left"</span>, va<span class="op">=</span><span class="st">"bottom"</span>, fontsize<span class="op">=</span><span class="fl">8.5</span>, color<span class="op">=</span>TEXT_MUTED, zorder<span class="op">=</span>LABEL_Z)</span>
<span id="cb25-105"><a href="#cb25-105" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="kw">not</span> np.isclose(forecast, cap, rtol<span class="op">=</span><span class="fl">0.001</span>):  <span class="co"># skip only when 2055 == capacity (The Point) -- avoids a duplicate label</span></span>
<span id="cb25-106"><a href="#cb25-106" aria-hidden="true" tabindex="-1"></a>            ax.text(forecast, top_y <span class="op">+</span> <span class="fl">0.07</span>, <span class="ss">f"</span><span class="sc">{</span>forecast<span class="sc">:,.0f}</span><span class="ss">"</span>, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"bottom"</span>, fontsize<span class="op">=</span><span class="fl">8.5</span>, color<span class="op">=</span>TEXT_MUTED, zorder<span class="op">=</span>LABEL_Z)</span>
<span id="cb25-107"><a href="#cb25-107" aria-hidden="true" tabindex="-1"></a>        ax.text(cap <span class="op">+</span> xmax <span class="op">*</span> <span class="fl">0.015</span>, y, <span class="ss">f"</span><span class="sc">{</span>cap<span class="sc">:,.0f}</span><span class="ss">"</span>, ha<span class="op">=</span><span class="st">"left"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">11</span>, color<span class="op">=</span>TEXT_PRIMARY,</span>
<span id="cb25-108"><a href="#cb25-108" aria-hidden="true" tabindex="-1"></a>                fontfamily<span class="op">=</span><span class="st">"Poppins SemiBold"</span>, zorder<span class="op">=</span>LABEL_Z,</span>
<span id="cb25-109"><a href="#cb25-109" aria-hidden="true" tabindex="-1"></a>                path_effects<span class="op">=</span>[pe.withStroke(linewidth<span class="op">=</span><span class="dv">3</span>, foreground<span class="op">=</span>SURFACE)])</span>
<span id="cb25-110"><a href="#cb25-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-111"><a href="#cb25-111" aria-hidden="true" tabindex="-1"></a>        <span class="co"># --- sensitivity overlay ---</span></span>
<span id="cb25-112"><a href="#cb25-112" aria-hidden="true" tabindex="-1"></a>        alt_pairs <span class="op">=</span> <span class="bu">list</span>(<span class="bu">zip</span>(cfg[<span class="st">"alt_ticks"</span>], (alt[(center, s)] <span class="cf">for</span> s <span class="kw">in</span> cfg[<span class="st">"alt_scenarios"</span>])))</span>
<span id="cb25-113"><a href="#cb25-113" aria-hidden="true" tabindex="-1"></a>        in_range <span class="op">=</span> [(lab, v) <span class="cf">for</span> lab, v <span class="kw">in</span> alt_pairs <span class="cf">if</span> v <span class="op">&lt;=</span> clip_limit]</span>
<span id="cb25-114"><a href="#cb25-114" aria-hidden="true" tabindex="-1"></a>        clipped <span class="op">=</span> [(lab, v) <span class="cf">for</span> lab, v <span class="kw">in</span> alt_pairs <span class="cf">if</span> v <span class="op">&gt;</span> clip_limit]</span>
<span id="cb25-115"><a href="#cb25-115" aria-hidden="true" tabindex="-1"></a>        tick_top, tick_bot <span class="op">=</span> y <span class="op">+</span> bar_height <span class="op">/</span> <span class="dv">2</span> <span class="op">+</span> <span class="fl">0.09</span>, y <span class="op">-</span> bar_height <span class="op">/</span> <span class="dv">2</span> <span class="op">-</span> <span class="fl">0.09</span></span>
<span id="cb25-116"><a href="#cb25-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-117"><a href="#cb25-117" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> in_range:</span>
<span id="cb25-118"><a href="#cb25-118" aria-hidden="true" tabindex="-1"></a>            vals <span class="op">=</span> [v <span class="cf">for</span> _, v <span class="kw">in</span> in_range]</span>
<span id="cb25-119"><a href="#cb25-119" aria-hidden="true" tabindex="-1"></a>            ax.plot([<span class="bu">min</span>(vals), <span class="bu">max</span>(vals)], [y, y], color<span class="op">=</span>BRACKET_INK, linewidth<span class="op">=</span><span class="fl">1.4</span>, zorder<span class="op">=</span><span class="dv">4</span>, solid_capstyle<span class="op">=</span><span class="st">"round"</span>)</span>
<span id="cb25-120"><a href="#cb25-120" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> lab, v <span class="kw">in</span> in_range:</span>
<span id="cb25-121"><a href="#cb25-121" aria-hidden="true" tabindex="-1"></a>                sc_color <span class="op">=</span> cfg[<span class="st">"scenario_colors"</span>][lab]</span>
<span id="cb25-122"><a href="#cb25-122" aria-hidden="true" tabindex="-1"></a>                ax.plot([v, v], [tick_bot, tick_top], color<span class="op">=</span>sc_color, linewidth<span class="op">=</span><span class="dv">2</span>, zorder<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb25-123"><a href="#cb25-123" aria-hidden="true" tabindex="-1"></a>                ax.text(v, tick_bot <span class="op">-</span> <span class="fl">0.03</span>, <span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:,.0f}</span><span class="ss">"</span>, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"top"</span>, fontsize<span class="op">=</span><span class="fl">7.6</span>,</span>
<span id="cb25-124"><a href="#cb25-124" aria-hidden="true" tabindex="-1"></a>                        color<span class="op">=</span>sc_color, fontfamily<span class="op">=</span><span class="st">"Poppins SemiBold"</span>, zorder<span class="op">=</span>LABEL_Z)</span>
<span id="cb25-125"><a href="#cb25-125" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> clipped:</span>
<span id="cb25-126"><a href="#cb25-126" aria-hidden="true" tabindex="-1"></a>            any_clipped <span class="op">=</span> <span class="va">True</span></span>
<span id="cb25-127"><a href="#cb25-127" aria-hidden="true" tabindex="-1"></a>            edge_x <span class="op">=</span> xmax <span class="op">*</span> <span class="fl">0.955</span></span>
<span id="cb25-128"><a href="#cb25-128" aria-hidden="true" tabindex="-1"></a>            ax.plot([edge_x], [y], marker<span class="op">=</span><span class="st">"&gt;"</span>, markersize<span class="op">=</span><span class="dv">6</span>, color<span class="op">=</span>BRACKET_INK, zorder<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb25-129"><a href="#cb25-129" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> idx, (lab, v) <span class="kw">in</span> <span class="bu">enumerate</span>(<span class="bu">sorted</span>(clipped, key<span class="op">=</span><span class="kw">lambda</span> t: t[<span class="dv">1</span>])):</span>
<span id="cb25-130"><a href="#cb25-130" aria-hidden="true" tabindex="-1"></a>                sc_color <span class="op">=</span> cfg[<span class="st">"scenario_colors"</span>][lab]</span>
<span id="cb25-131"><a href="#cb25-131" aria-hidden="true" tabindex="-1"></a>                ax.text(edge_x <span class="op">+</span> xmax <span class="op">*</span> <span class="fl">0.01</span>, tick_bot <span class="op">-</span> <span class="fl">0.03</span> <span class="op">-</span> idx <span class="op">*</span> <span class="fl">0.15</span>, <span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:,.0f}</span><span class="ss">*"</span>, ha<span class="op">=</span><span class="st">"left"</span>, va<span class="op">=</span><span class="st">"top"</span>,</span>
<span id="cb25-132"><a href="#cb25-132" aria-hidden="true" tabindex="-1"></a>                        fontsize<span class="op">=</span><span class="fl">7.6</span>, color<span class="op">=</span>sc_color, fontfamily<span class="op">=</span><span class="st">"Poppins SemiBold"</span>, zorder<span class="op">=</span>LABEL_Z)</span>
<span id="cb25-133"><a href="#cb25-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-134"><a href="#cb25-134" aria-hidden="true" tabindex="-1"></a>    ax.set_yticks(ys)</span>
<span id="cb25-135"><a href="#cb25-135" aria-hidden="true" tabindex="-1"></a>    ax.set_yticklabels([CENTER_LABELS[c] <span class="cf">for</span> c <span class="kw">in</span> order], fontsize<span class="op">=</span><span class="dv">11</span>, color<span class="op">=</span>TEXT_PRIMARY)</span>
<span id="cb25-136"><a href="#cb25-136" aria-hidden="true" tabindex="-1"></a>    ax.set_xlim(<span class="dv">0</span>, xmax <span class="op">*</span> <span class="fl">1.2</span>)</span>
<span id="cb25-137"><a href="#cb25-137" aria-hidden="true" tabindex="-1"></a>    ax.set_ylim(<span class="op">-</span><span class="fl">0.75</span>, ys[<span class="op">-</span><span class="dv">1</span>] <span class="op">+</span> <span class="fl">0.95</span>)</span>
<span id="cb25-138"><a href="#cb25-138" aria-hidden="true" tabindex="-1"></a>    ax.get_xaxis().set_visible(<span class="va">False</span>)</span>
<span id="cb25-139"><a href="#cb25-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-140"><a href="#cb25-140" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> spine <span class="kw">in</span> ax.spines.values():</span>
<span id="cb25-141"><a href="#cb25-141" aria-hidden="true" tabindex="-1"></a>        spine.set_visible(<span class="va">False</span>)</span>
<span id="cb25-142"><a href="#cb25-142" aria-hidden="true" tabindex="-1"></a>    ax.tick_params(left<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb25-143"><a href="#cb25-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-144"><a href="#cb25-144" aria-hidden="true" tabindex="-1"></a>    fig.suptitle(cfg[<span class="st">"title"</span>], x<span class="op">=</span><span class="fl">0.03</span>, y<span class="op">=</span><span class="fl">0.975</span>, fontsize<span class="op">=</span><span class="dv">17</span>, color<span class="op">=</span>TEXT_PRIMARY, ha<span class="op">=</span><span class="st">"left"</span>, fontfamily<span class="op">=</span><span class="st">"Poppins SemiBold"</span>)</span>
<span id="cb25-145"><a href="#cb25-145" aria-hidden="true" tabindex="-1"></a>    fig.text(<span class="fl">0.03</span>, <span class="fl">0.875</span>, cfg[<span class="st">"subtitle"</span>], fontsize<span class="op">=</span><span class="fl">10.5</span>, color<span class="op">=</span>TEXT_MUTED, ha<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb25-146"><a href="#cb25-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-147"><a href="#cb25-147" aria-hidden="true" tabindex="-1"></a>    tier_legend <span class="op">=</span> [</span>
<span id="cb25-148"><a href="#cb25-148" aria-hidden="true" tabindex="-1"></a>        Patch(facecolor<span class="op">=</span>TEXT_MUTED, label<span class="op">=</span><span class="st">"2025 (current)"</span>),</span>
<span id="cb25-149"><a href="#cb25-149" aria-hidden="true" tabindex="-1"></a>        Patch(facecolor<span class="op">=</span><span class="st">"none"</span>, edgecolor<span class="op">=</span>TEXT_MUTED, hatch<span class="op">=</span><span class="st">"///"</span>, label<span class="op">=</span><span class="st">"2055 (forecast)"</span>),</span>
<span id="cb25-150"><a href="#cb25-150" aria-hidden="true" tabindex="-1"></a>        Patch(facecolor<span class="op">=</span>lighten(TEXT_MUTED, <span class="fl">0.7</span>), label<span class="op">=</span><span class="st">"Full REMM capacity"</span>),</span>
<span id="cb25-151"><a href="#cb25-151" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb25-152"><a href="#cb25-152" aria-hidden="true" tabindex="-1"></a>    scenario_legend <span class="op">=</span> [</span>
<span id="cb25-153"><a href="#cb25-153" aria-hidden="true" tabindex="-1"></a>        Line2D([<span class="dv">0</span>], [<span class="dv">0</span>], color<span class="op">=</span>color, marker<span class="op">=</span><span class="st">"|"</span>, markersize<span class="op">=</span><span class="dv">10</span>, markeredgewidth<span class="op">=</span><span class="fl">2.2</span>, linestyle<span class="op">=</span><span class="st">"-"</span>, linewidth<span class="op">=</span><span class="fl">1.6</span>, label<span class="op">=</span>lab)</span>
<span id="cb25-154"><a href="#cb25-154" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> lab, color <span class="kw">in</span> cfg[<span class="st">"scenario_colors"</span>].items()</span>
<span id="cb25-155"><a href="#cb25-155" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb25-156"><a href="#cb25-156" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Two independently self-centered legend rows (not one grid -- forcing</span></span>
<span id="cb25-157"><a href="#cb25-157" aria-hidden="true" tabindex="-1"></a>    <span class="co"># jobs's 2 scenario items into a 3-wide grid to match the 3 tier items</span></span>
<span id="cb25-158"><a href="#cb25-158" aria-hidden="true" tabindex="-1"></a>    <span class="co"># packs them left instead of centering them). Anchor x is 0.5 (true</span></span>
<span id="cb25-159"><a href="#cb25-159" aria-hidden="true" tabindex="-1"></a>    <span class="co"># figure center), not the axes' own geometric center: the axes reserves</span></span>
<span id="cb25-160"><a href="#cb25-160" aria-hidden="true" tabindex="-1"></a>    <span class="co"># ~20% of extra width on its right for value labels beyond the bars</span></span>
<span id="cb25-161"><a href="#cb25-161" aria-hidden="true" tabindex="-1"></a>    <span class="co"># (xlim goes to xmax*1.2) with nothing mirrored on the left, so the bars</span></span>
<span id="cb25-162"><a href="#cb25-162" aria-hidden="true" tabindex="-1"></a>    <span class="co"># themselves visually center close to figure fraction 0.5.</span></span>
<span id="cb25-163"><a href="#cb25-163" aria-hidden="true" tabindex="-1"></a>    legend_kwargs <span class="op">=</span> <span class="bu">dict</span>(loc<span class="op">=</span><span class="st">"upper center"</span>, frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">9</span>, handlelength<span class="op">=</span><span class="fl">1.4</span>,</span>
<span id="cb25-164"><a href="#cb25-164" aria-hidden="true" tabindex="-1"></a>                          columnspacing<span class="op">=</span><span class="fl">1.3</span>, bbox_transform<span class="op">=</span>fig.transFigure)</span>
<span id="cb25-165"><a href="#cb25-165" aria-hidden="true" tabindex="-1"></a>    legend1 <span class="op">=</span> fig.legend(handles<span class="op">=</span>tier_legend, bbox_to_anchor<span class="op">=</span>(<span class="fl">0.5</span>, <span class="fl">0.82</span>), ncol<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb25-166"><a href="#cb25-166" aria-hidden="true" tabindex="-1"></a>                          labelcolor<span class="op">=</span>TEXT_MUTED, <span class="op">**</span>legend_kwargs)</span>
<span id="cb25-167"><a href="#cb25-167" aria-hidden="true" tabindex="-1"></a>    fig.add_artist(legend1)</span>
<span id="cb25-168"><a href="#cb25-168" aria-hidden="true" tabindex="-1"></a>    fig.legend(handles<span class="op">=</span>scenario_legend, bbox_to_anchor<span class="op">=</span>(<span class="fl">0.5</span>, <span class="fl">0.775</span>),</span>
<span id="cb25-169"><a href="#cb25-169" aria-hidden="true" tabindex="-1"></a>               ncol<span class="op">=</span><span class="bu">len</span>(scenario_legend), <span class="op">**</span>legend_kwargs)</span>
<span id="cb25-170"><a href="#cb25-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-171"><a href="#cb25-171" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> any_clipped:</span>
<span id="cb25-172"><a href="#cb25-172" aria-hidden="true" tabindex="-1"></a>        fig.text(<span class="fl">0.03</span>, <span class="fl">0.02</span>, <span class="st">"* beyond this chart's scale -- marked &gt; on its row"</span>, fontsize<span class="op">=</span><span class="dv">8</span>, color<span class="op">=</span>TEXT_MUTED,</span>
<span id="cb25-173"><a href="#cb25-173" aria-hidden="true" tabindex="-1"></a>                  ha<span class="op">=</span><span class="st">"left"</span>, style<span class="op">=</span><span class="st">"italic"</span>)</span>
<span id="cb25-174"><a href="#cb25-174" aria-hidden="true" tabindex="-1"></a>    fig.text(<span class="fl">0.97</span>, <span class="fl">0.02</span>, <span class="st">"Source: REMM 2055 run (WFRC)"</span>, fontsize<span class="op">=</span><span class="dv">8</span>, color<span class="op">=</span>TEXT_MUTED, ha<span class="op">=</span><span class="st">"right"</span>, style<span class="op">=</span><span class="st">"italic"</span>)</span>
<span id="cb25-175"><a href="#cb25-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-176"><a href="#cb25-176" aria-hidden="true" tabindex="-1"></a>    plt.subplots_adjust(top<span class="op">=</span><span class="fl">0.68</span>, bottom<span class="op">=</span><span class="fl">0.08</span>, left<span class="op">=</span>LEFT, right<span class="op">=</span>RIGHT)</span>
<span id="cb25-177"><a href="#cb25-177" aria-hidden="true" tabindex="-1"></a>    plt.savefig(output_dir <span class="op">/</span> cfg[<span class="st">"out"</span>], facecolor<span class="op">=</span>fig.get_facecolor())</span>
<span id="cb25-178"><a href="#cb25-178" aria-hidden="true" tabindex="-1"></a>    plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="0a509087" class="cell" data-execution_count="22">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>make_chart(<span class="st">"jobs"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-23-output-1.png" width="1278" height="865" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="962bc864" class="cell" data-execution_count="23">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>make_chart(<span class="st">"housing"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-24-output-1.png" width="1278" height="865" class="figure-img"></p>
</figure>
</div>
</div>
</div>


</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/wfrcanalytics\.github\.io\/GIS-adhoc-analyses");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 <a href="https://wfrc.utah.gov/">Wasatch Front Regional Council</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>